  
networks:
  server-network:
    driver: bridge

services:
  gateway:
    build: ./microservices/gateway
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ${CERTIFICATE_DIR:-./certificates}:/etc/nginx/certs:rw
    depends_on:
      - map-tile-service
      - route-service
    networks:
      - server-network
    profiles:
      - development
      - production

  map-tile-service:
    build:
      context: ./microservices/typescript_services
      target: map-tile-service
    depends_on:
      - redis
    networks:
      - server-network
    profiles:
      - development
      - production

  route-service:
    build:
      context: ./microservices/typescript_services
      target: route-service
    depends_on:
      - graphhopper
    networks:
      - server-network
    profiles:
      - development
      - production

  graphhopper:
    # non esiste un'immagine docker ufficiale per graphhopper
    # l'immagine più utilizzata nella community sembra essere questa
    image: "israelhikingmap/graphhopper:10.2"
    env_file: .env
    environment:
      JAVA_OPTS: "${GRAPH_HOPPER_JAVA_ARGS}"
    volumes:
      - ./microservices/graphhopper/data:/data
    command: |-
      --input /data/map_data.pbf
    networks:
      - server-network
    profiles:
      - development
      - production
      
  redis:
    image: redis:7
    volumes:
      - ./microservices/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./microservices/redis/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - server-network
    profiles:
      - development
      - production
      